### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by TheMrKochan** [sgkoishi/PackTracker#42]
Make sure you are using the latest version of the Plugin and HDT.

System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at PackTracker.Update.Updater.Update() in D:\a\PackTracker\PackTracker\PackHistorian\Update\Updater.cs:line 41
   at PackTracker.Controls.Settings.Update.<btn_Update_Click>b__9_0(Object bwsender, DoWorkEventArgs bwe) in D:\a\PackTracker\PackTracker\PackHistorian\Controls\Settings\Update.xaml.cs:line 117
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at System.ComponentModel.RunWorkerCompletedEventArgs.get_Result()
   at PackTracker.Controls.Settings.Update.<btn_Update_Click>b__9_1(Object bwsender, RunWorkerCompletedEventArgs bwe) in D:\a\PackTracker\PackTracker\PackHistorian\Controls\Settings\Update.xaml.cs:line 122
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by sgkoishi** [comment]
Fixed.
